name: mobile
description: Find Up!
publish_to: 'none'

version: 1.2.0+19

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ilp_file_codec:
    path: ../../package/ilp_file_codec
  game:
    path: ../../package/game
  ui:
    path: ../../package/ui
  ilp_assets:
    path: ../../package/ilp_assets

  amplify_storage_s3: ^0.2.5
  get: ^4.6.6
  oktoast: ^3.4.0
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3
  firebase_core: ^2.29.0
  dynamic_color: ^1.7.0
  change_app_package_name: ^1.1.0
  url_launcher: ^6.2.5
  package_info_plus: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.5.0
  flutter_staggered_grid_view: ^0.7.0
  unity_ads_plugin: ^0.3.13
  google_fonts: ^6.2.1
  yaml_edit: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_launcher_icons:
  android: "ic_launcher"
  #  ios: true
  image_path: "logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true